name: bibliotheca
services:
  bibliotheca-node:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: bibliotheca-node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${NODE_PORT:-3000}:${NODE_PORT:-3000}"
    command: tail -f /dev/null
    depends_on:
      - bibliotheca-postgres

  bibliotheca-postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: bibliotheca-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST_AUTH_METHOD: password
