CREATE DATABASE IF NOT EXISTS bibliotheca;

CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
username VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,  
hashed_password VARCHAR(255) NOT NULL,  
date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE IF NOT EXISTS authors (
id SERIAL PRIMARY KEY,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
UNIQUE(first_name, last_name)
);

CREATE TABLE IF NOT EXISTS genres (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
author_id INTEGER REFERENCES authors(id) NOT NULL,
genre_id INTEGER REFERENCES genres(id) NOT NULL,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) NOT NULL,
book_id INTEGER REFERENCES books(id) NOT NULL,
rating INTEGER NOT NULL,
review VARCHAR(255),
date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);